### ISSUE TITLE
Mismatched angular dependencies

### ISSUE THREAD

**Issue by andy-dorman** [wingedfox/dgeni-alive#17]
Hi,

Our doc build has recently started failing - I suspect since angular 1.6 dropped.

We're getting this:

```
Uncaught Error: [$injector:unpr] Unknown provider: $$isDocumentHiddenProvider <- $$isDocumentHidden <- $$animateQueue <- $animate <- $compile <- $$animateQueue
```

It's caused because the angular depdency is set to 1.5.x but somewhere else there is an angaulr-animate dependency that is now at 1.6 - you can see this by looking in the generated bower_components directory. This can be fixed by specifiying a matching versionsin:

```
packages > website > templates > website > bower.json
```

angular: 1.5.9
angular-animate: 1.5.9

seems to work, it doesn't look ready for 1.6 yet - I know our application certainly isn't...

So two questions really:

1. Do you want me to submit a pull request to fix it?
or
2. Is there a way of overriding the bower.json file used in the generateWebsiteProcessor?

**Comment by deemstone** [comment]
+1
add ```"angular-animate": "1.5.9"``` to bower.json > dependencies & resolutions, that's work!

**Comment by wingedfox** [comment]
@andy-dorman, thank you for reporting.

@deemstone, could you, please, update PR with either 1.5.9 or 1.5.x in the both dependencies or test ui against angular-1.6? Thank you.

**Comment by gbbr** [comment]
This issue is happening to me too...

**Comment by wingedfox** [comment]
@andy-dorman, thank you, merged.

**Comment by amiteshhh** [comment]
Again its not working. Similar to issue #17
**Uncaught Error: [$injector:unpr] Unknown provider: $$MapProvider**
Looks like ngAnimate is expecting angular 1.6.x.
Since ngAnimate is getting installed via ngMaterialize, is there something wrong in bower dependency of ngMaterialize?

Adding `"angular-animate": "1.6.x"` to _bower.json_ dependencies & resolutions is solving the problem!
`node_modules > dgeni-alive > src > packages > website > templates > website > bower.json`
